### ISSUE TITLE
Shortcut change does not stick

### ISSUE THREAD

**Issue by KristjanLaane** [strike-digital/node_pie#7]
I change shortcut under your addon options. It works fine. I close Blender. When I run Blender next time the shortcut has reverted to the default of Ctrl Left Mouse.

**Comment by nurb2kea** [comment]
Have you saved preferences after changing the shortcut key?
![Screenshot 2022-11-07 at 12 50 14 am](https://user-images.githubusercontent.com/57676085/200202345-b019946d-e988-49cd-9a26-d41de5a09c7e.jpg)

**Comment by KristjanLaane** [comment]
1) I have auto-save preferences on. 
2) pressed on Save Preferences manually just now, to see if that helps, but it does, reverts back to Ctrl LMB after blender restart. 
(using blender 3.3.1)

**Comment by nurb2kea** [comment]
Only thing I can think of is to find in the the addon script the part where Ctrl LMB is set and change it to something else, BUT that onlt temporary and will be overwritten next time you update the script.

So, I guess it's maybe better to wait for the answer/fix from the dev. !!

**Comment by strike-digital** [comment]
Hi, after a long rabbit hole of research, it seems like this is a long-standing problem with blender that I couldn't find an official solution to anywhere.

There's probably some hacky way that I can get it to work though, so I'll give that a try now...

**Comment by nurb2kea** [comment]
This blender problem must then only be on windows.
In the meantime until the dev comes up with a solution try to open the marked file in your addon folder with a basic text editor & make your changes there and save. (just replace the text between the ' ' otherwise you can break the code)
When saved leave it open, in case you want to change back.
This is from my addon dir, so you see I used CTRL+A. Change it to what you like.
The CTRL+leftmouse is also working.(but it's not coming up in the addon preferences) 

So that's just the temp. solution. 
I guess when the dev is online again, he can help.

You also can delete the '__pycache__' - Folder to reset the addon, it will be rebuild when you startup blender again. 
(Maybe this can be the issue too if it doesn't have the right to be written/overwritten by the OS  )

![Screenshot 2022-11-07 at 4 19 48 pm](https://user-images.githubusercontent.com/57676085/200347755-bd35442f-31d9-4152-a3c8-5fba1bc01591.jpg)

**Comment by strike-digital** [comment]
Ok, this should now be fixed in the latest release

**Comment by KristjanLaane** [comment]
i found time to try it out, but now Blender errors out when i try to enable the addon:
![image](https://user-images.githubusercontent.com/1708294/203146642-8e70c980-ff59-44eb-bb7c-957a1e42435d.png)

p.s. thank you @nurb2kea for the interim solution

**Comment by strike-digital** [comment]
Ah, thanks for pointing that out, it should be fixed now :)

**Comment by KristjanLaane** [comment]
thank you, installs/enables fine now. but unfortunately the shortcuts still dont stick:
![stillRevertsBack](https://user-images.githubusercontent.com/1708294/203411358-055f1777-4ce8-4881-8862-51b026bf07e0.gif)

**Comment by SophonHuang** [comment]
Open the zip file, find  the key that you don't want it, and delete it, Restart and reinstall maybe will be work  :>
![1_release](https://user-images.githubusercontent.com/59360357/218792435-50a3456b-4c97-4f05-b757-65bf7bc3cd06.png)
![2_Delete the Key and save](https://user-images.githubusercontent.com/59360357/218792444-608450cf-cf53-41d0-a257-49c5c8c67af2.png)
![3_Reinstall it](https://user-images.githubusercontent.com/59360357/218792456-f385b534-105b-4de7-981c-be8be368cea6.png)

**Comment by strike-digital** [comment]
Hi, sorry this has taken a while, fingers crossed this should be fixed in the latest release 🤞

**Comment by KristjanLaane** [comment]
When I click the plus button and add a new shortcut then it works and sticks after restarting Blender:
![image](https://github.com/strike-digital/node_pie/assets/1708294/c3fd1deb-1633-47db-ae60-78a3f510d812)
When i change the default existing shortcut, it does not stick after restart still. 
But given i know it works through the plus button, then for my purposes it works now! Thanks!

**Comment by strike-digital** [comment]
Hmm, ok, getting closer 😅
Just to make sure, are you using version 1.2.9?

**Comment by KristjanLaane** [comment]
Yes.

**Comment by strike-digital** [comment]
Hmm, ok, and are you saving the preferences before closing Blender?

After having another look at the code, I can't really think what else it could be, especially as it's working for me 😅

**Comment by KristjanLaane** [comment]
i dont really have time to troubleshoot this further, it works for my purposes now with the plus button. i think it is ok to close this issue now :)

**Comment by strike-digital** [comment]
No worries, thanks for using the addon!
